/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dd_sdl_com_jnik_MFRC522 */

#ifndef _Included_dd_sdl_com_jnik_MFRC522
#define _Included_dd_sdl_com_jnik_MFRC522
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    PcdReset
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_dd_sdl_com_jnik_MFRC522_PcdReset
  (JNIEnv *, jclass);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    PcdAntennaOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dd_sdl_com_jnik_MFRC522_PcdAntennaOn
  (JNIEnv *, jclass);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    PcdAntennaOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dd_sdl_com_jnik_MFRC522_PcdAntennaOff
  (JNIEnv *, jclass);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    PcdRequest
 * Signature: (CC)C
 */
JNIEXPORT jchar JNICALL Java_dd_sdl_com_jnik_MFRC522_PcdRequest
  (JNIEnv *, jclass, jchar, jchar);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    PcdAnticoll
 * Signature: (C)C
 */
JNIEXPORT jchar JNICALL Java_dd_sdl_com_jnik_MFRC522_PcdAnticoll
  (JNIEnv *, jclass, jchar);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    PcdSelect
 * Signature: (C)C
 */
JNIEXPORT jchar JNICALL Java_dd_sdl_com_jnik_MFRC522_PcdSelect
  (JNIEnv *, jclass, jchar);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    PcdAuthState
 * Signature: (CCCC)C
 */
JNIEXPORT jchar JNICALL Java_dd_sdl_com_jnik_MFRC522_PcdAuthState
  (JNIEnv *, jclass, jchar, jchar, jchar, jchar);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    PcdRead
 * Signature: (CC)C
 */
JNIEXPORT jchar JNICALL Java_dd_sdl_com_jnik_MFRC522_PcdRead
  (JNIEnv *, jclass, jchar, jchar);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    PcdWrite
 * Signature: (CC)C
 */
JNIEXPORT jchar JNICALL Java_dd_sdl_com_jnik_MFRC522_PcdWrite
  (JNIEnv *, jclass, jchar, jchar);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    PcdValue
 * Signature: (CCC)C
 */
JNIEXPORT jchar JNICALL Java_dd_sdl_com_jnik_MFRC522_PcdValue
  (JNIEnv *, jclass, jchar, jchar, jchar);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    PcdBakValue
 * Signature: (CC)C
 */
JNIEXPORT jchar JNICALL Java_dd_sdl_com_jnik_MFRC522_PcdBakValue
  (JNIEnv *, jclass, jchar, jchar);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    PcdHalt
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_dd_sdl_com_jnik_MFRC522_PcdHalt
  (JNIEnv *, jclass);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    PcdComMF522
 * Signature: (CCCCI)C
 */
JNIEXPORT jchar JNICALL Java_dd_sdl_com_jnik_MFRC522_PcdComMF522
  (JNIEnv *, jclass, jchar, jchar, jchar, jchar, jint);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    CalulateCRC
 * Signature: (CCC)V
 */
JNIEXPORT void JNICALL Java_dd_sdl_com_jnik_MFRC522_CalulateCRC
  (JNIEnv *, jclass, jchar, jchar, jchar);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    WriteRawRC
 * Signature: (CC)V
 */
JNIEXPORT void JNICALL Java_dd_sdl_com_jnik_MFRC522_WriteRawRC
  (JNIEnv *, jclass, jchar, jchar);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    ReadRawRC
 * Signature: (C)C
 */
JNIEXPORT jchar JNICALL Java_dd_sdl_com_jnik_MFRC522_ReadRawRC
  (JNIEnv *, jclass, jchar);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    SetBitMask
 * Signature: (CC)V
 */
JNIEXPORT void JNICALL Java_dd_sdl_com_jnik_MFRC522_SetBitMask
  (JNIEnv *, jclass, jchar, jchar);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    ClearBitMask
 * Signature: (CC)V
 */
JNIEXPORT void JNICALL Java_dd_sdl_com_jnik_MFRC522_ClearBitMask
  (JNIEnv *, jclass, jchar, jchar);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    M500PcdConfigISOType
 * Signature: (C)C
 */
JNIEXPORT jchar JNICALL Java_dd_sdl_com_jnik_MFRC522_M500PcdConfigISOType
  (JNIEnv *, jclass, jchar);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    delay_10ms
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dd_sdl_com_jnik_MFRC522_delay_110ms
  (JNIEnv *, jclass, jint);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    WaitCardOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dd_sdl_com_jnik_MFRC522_WaitCardOff
  (JNIEnv *, jclass);

/*
 * Class:     dd_sdl_com_jnik_MFRC522
 * Method:    getStrFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dd_sdl_com_jnik_MFRC522_getStrFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
