/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dd_sdl_com_myapplication_GPIOControl */

#ifndef _Included_dd_sdl_com_myapplication_GPIOControl
#define _Included_dd_sdl_com_myapplication_GPIOControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dd_sdl_com_myapplication_GPIOControl
 * Method:    nativeReadGpio
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_dd_sdl_com_myapplication_GPIOControl_nativeReadGpio
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dd_sdl_com_myapplication_GPIOControl
 * Method:    nativeWriteGpio
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_dd_sdl_com_myapplication_GPIOControl_nativeWriteGpio
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
